-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfRn26EzbvQRgclp9
gUncaXyUlpeRJaWP6aKSlaf7knmgCgYIKoZIzj0DAQehRANCAARF0PAkwEGzxXR0
obUMSsFV3t3xdRCR/6z3RguuViXYmK9MZEeHUnuCytMIf2TUr7HCeUfBTFXcYjdT
0V304XEw
-----END PRIVATE KEY-----